<?php
/**
 * Reading and walking the Elementor element tree stored on a post.
 *
 * The tree lives in the _elementor_data meta row as JSON. Node shape, verified
 * against Elementor 4.2.2:
 *
 *   containers:  { id, elType, settings, elements, isInner }
 *   widgets:     { id, elType, settings, elements, widgetType }
 *
 * Element IDs are seven-character strings generated by the editor. They are unique
 * within a page in practice but nothing enforces it, so anything that resolves an
 * ID must handle the ambiguous case rather than taking the first match.
 *
 * Real pages reach megabytes, so every read is bounded: the raw value is size-
 * checked before it is decoded, the walk is depth-capped, and the number of nodes
 * returned is capped with an explicit "there are more" signal rather than silent
 * truncation.
 *
 * @package Mosmcp_Abilities_Library
 */

namespace MoSMCP\Abilities\Packs\Elementor;

use WP_Error;
use WP_Post;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/*
 * This library authors every translatable string under its own fixed text domain
 * ('mosmcp-abilities'). The host plugin remaps them to its own text domain at
 * runtime via Abilities_Library::init(). The domain therefore intentionally will
 * not match any host plugin's slug, so the text-domain-mismatch check is disabled
 * for this file (the library's phpcs.xml.dist allows the domain on the CLI; this
 * directive covers IDE and Plugin Check runs that don't load that ruleset).
 */
// phpcs:disable WordPress.WP.I18n.TextDomainMismatch

/**
 * Class Elementor_Document
 */
class Elementor_Document {

	/**
	 * The meta key holding the element tree.
	 *
	 * @var string
	 */
	const DATA_KEY = '_elementor_data';

	/**
	 * The meta key marking a post as built with Elementor ('builder').
	 *
	 * @var string
	 */
	const EDIT_MODE_KEY = '_elementor_edit_mode';

	/**
	 * The meta key holding the Elementor template type (e.g. 'wp-page').
	 *
	 * @var string
	 */
	const TEMPLATE_TYPE_KEY = '_elementor_template_type';

	/**
	 * Largest raw tree this pack will decode, in bytes.
	 *
	 * Decoding costs roughly ten times the JSON size in PHP array overhead, so an
	 * eight-megabyte tree would approach a default memory limit on its own. Refusing
	 * with a clear message beats dying mid-request.
	 *
	 * @var int
	 */
	const MAX_DECODE_BYTES = 8388608;

	/**
	 * Deepest nesting the walker will descend.
	 *
	 * Guards against a cyclic or pathologically nested tree; genuine Elementor
	 * layouts are rarely deeper than six.
	 *
	 * @var int
	 */
	const MAX_DEPTH = 32;

	/**
	 * Default and maximum node counts for a summarised read.
	 *
	 * @var int
	 */
	const DEFAULT_LIMIT = 150;
	const MAX_LIMIT     = 1000;

	/**
	 * Whether a post carries an Elementor layout.
	 *
	 * @param int $post_id Post ID.
	 * @return bool
	 */
	public static function has_data( $post_id ) {
		return '' !== (string) get_post_meta( (int) $post_id, self::DATA_KEY, true );
	}

	/**
	 * The raw JSON tree as stored.
	 *
	 * @param int $post_id Post ID.
	 * @return string
	 */
	public static function raw( $post_id ) {
		$raw = get_post_meta( (int) $post_id, self::DATA_KEY, true );
		return is_string( $raw ) ? $raw : '';
	}

	/**
	 * Decodes the tree for a post.
	 *
	 * @param int $post_id Post ID.
	 * @return array<int, array<string, mixed>>|WP_Error
	 */
	public static function tree( $post_id ) {
		$post_id = (int) $post_id;
		$raw     = self::raw( $post_id );

		if ( '' === $raw ) {
			return new WP_Error(
				'no_elementor_data',
				__( 'This post has no Elementor layout. It was either built with the block editor or never opened in Elementor.', 'mosmcp-abilities' )
			);
		}

		$bytes = strlen( $raw );
		if ( $bytes > self::MAX_DECODE_BYTES ) {
			return new WP_Error(
				'elementor_data_too_large',
				sprintf(
					/* translators: 1: actual size in bytes, 2: limit in bytes */
					__( 'This Elementor layout is %1$s bytes, above the %2$s byte limit this tool will load into memory. Edit it in Elementor directly.', 'mosmcp-abilities' ),
					number_format_i18n( $bytes ),
					number_format_i18n( self::MAX_DECODE_BYTES )
				)
			);
		}

		$tree = json_decode( $raw, true );

		if ( ! is_array( $tree ) ) {
			/*
			 * Deliberately does NOT suggest opening the post in Elementor and saving.
			 * Elementor cannot parse this data either, so it loads a document with
			 * zero elements: the canvas appears empty and pressing Update writes that
			 * empty canvas over whatever is still in the row. The advice would destroy
			 * the layout rather than repair it, which is the opposite of what someone
			 * reading an error message is looking for.
			 */
			return new WP_Error(
				'elementor_data_unreadable',
				sprintf(
					/* translators: %s: JSON error message */
					__( 'The stored Elementor layout is not valid JSON and cannot be read (%s). Do not open this post in Elementor and save it: Elementor cannot read the layout either, so it will show an empty canvas and saving would overwrite what remains. Re-create the post from the one it was copied from instead.', 'mosmcp-abilities' ),
					function_exists( 'json_last_error_msg' ) ? json_last_error_msg() : 'unknown error'
				)
			);
		}

		return $tree;
	}

	/**
	 * Resolves a post and confirms it carries a readable Elementor tree.
	 *
	 * @param int $post_id Post ID.
	 * @return WP_Post|WP_Error
	 */
	public static function require_post( $post_id ) {
		$post_id = absint( $post_id );
		$post    = $post_id > 0 ? get_post( $post_id ) : null;

		if ( ! $post ) {
			return new WP_Error(
				'post_not_found',
				__( 'No post or page found with that ID.', 'mosmcp-abilities' )
			);
		}

		return $post;
	}

	/**
	 * Walks the tree depth-first, calling $visit for every node.
	 *
	 * $visit receives ( array $node, int[] $path, int $depth ) and may return false
	 * to stop the walk early.
	 *
	 * @param array<int, mixed> $nodes Tree or subtree.
	 * @param callable          $visit Visitor.
	 * @param int[]             $path  Accumulated index path.
	 * @param int               $depth Current depth.
	 * @return bool False when the visitor asked to stop.
	 */
	public static function walk( array $nodes, callable $visit, array $path = array(), $depth = 0 ) {
		if ( $depth > self::MAX_DEPTH ) {
			return true;
		}

		foreach ( $nodes as $index => $node ) {
			if ( ! is_array( $node ) ) {
				continue;
			}

			$node_path = array_merge( $path, array( (int) $index ) );

			if ( false === call_user_func( $visit, $node, $node_path, $depth ) ) {
				return false;
			}

			if ( ! empty( $node['elements'] ) && is_array( $node['elements'] ) ) {
				if ( ! self::walk( $node['elements'], $visit, $node_path, $depth + 1 ) ) {
					return false;
				}
			}
		}

		return true;
	}

	/**
	 * Flattens a tree into a list of described nodes, content values included.
	 *
	 * @param array<int, mixed>    $tree    Decoded tree.
	 * @param array<string, mixed> $options 'limit', 'offset', 'max_depth', 'widget_type', 'search'.
	 * @return array<string, mixed>
	 */
	public static function summarize( array $tree, array $options = array() ) {
		$limit     = isset( $options['limit'] ) ? absint( $options['limit'] ) : self::DEFAULT_LIMIT;
		$limit     = max( 1, min( $limit, self::MAX_LIMIT ) );
		$offset    = isset( $options['offset'] ) ? absint( $options['offset'] ) : 0;
		$max_depth = isset( $options['max_depth'] ) ? absint( $options['max_depth'] ) : self::MAX_DEPTH;
		$type      = isset( $options['widget_type'] ) ? (string) $options['widget_type'] : '';
		$search    = isset( $options['search'] ) ? strtolower( trim( (string) $options['search'] ) ) : '';

		$nodes      = array();
		$total      = 0;
		$matched    = 0;
		$has_atomic = false;
		$counts     = array();

		self::walk(
			$tree,
			static function ( $node, $path, $depth ) use ( &$nodes, &$total, &$matched, &$has_atomic, &$counts, $limit, $offset, $max_depth, $type, $search ) {
				++$total;

				$described = self::describe_node( $node, $path, $depth );

				$key            = '' !== $described['widget_type'] ? $described['widget_type'] : $described['el_type'];
				$counts[ $key ] = isset( $counts[ $key ] ) ? $counts[ $key ] + 1 : 1;

				if ( $described['is_atomic'] ) {
					$has_atomic = true;
				}

				if ( $depth > $max_depth ) {
					return true;
				}
				if ( '' !== $type && $described['widget_type'] !== $type && $described['el_type'] !== $type ) {
					return true;
				}
				if ( '' !== $search && false === strpos( strtolower( wp_json_encode( $described['content'] ) ), $search ) ) {
					return true;
				}

				++$matched;

				if ( $matched > $offset && count( $nodes ) < $limit ) {
					$nodes[] = $described;
				}

				return true;
			}
		);

		arsort( $counts );

		return array(
			'nodes'          => $nodes,
			'returned'       => count( $nodes ),
			'matched'        => $matched,
			'total_elements' => $total,
			'has_more'       => $matched > ( $offset + count( $nodes ) ),
			'has_atomic'     => $has_atomic,
			'element_counts' => $counts,
		);
	}

	/**
	 * Describes one node: identity, position, and its content values.
	 *
	 * Styling settings are deliberately omitted. A container carries over two
	 * hundred of them and none help a caller decide what to read or change; the
	 * schema ability exists for when they are actually needed.
	 *
	 * @param array<string, mixed> $node  Node.
	 * @param int[]                $path  Index path.
	 * @param int                  $depth Depth.
	 * @return array<string, mixed>
	 */
	public static function describe_node( array $node, array $path, $depth ) {
		$el_type     = isset( $node['elType'] ) ? (string) $node['elType'] : '';
		$widget_type = isset( $node['widgetType'] ) ? (string) $node['widgetType'] : '';
		$slug        = '' !== $widget_type ? $widget_type : $el_type;
		$settings    = isset( $node['settings'] ) && is_array( $node['settings'] ) ? $node['settings'] : array();

		$element   = Elementor_Schema::element( $slug );
		$is_atomic = Elementor_Schema::is_atomic( $element );

		return array(
			'element_id'  => isset( $node['id'] ) ? (string) $node['id'] : '',
			'el_type'     => $el_type,
			'widget_type' => $widget_type,
			'title'       => $element && method_exists( $element, 'get_title' ) ? (string) $element->get_title() : $slug,
			'path'        => implode( '.', array_map( 'strval', $path ) ),
			'depth'       => (int) $depth,
			'child_count' => isset( $node['elements'] ) && is_array( $node['elements'] ) ? count( $node['elements'] ) : 0,
			'is_atomic'   => $is_atomic,
			'editable'    => ! $is_atomic || isset( Elementor_Schema::ATOMIC_CONTENT[ $slug ] ),
			'content'     => self::content_values( $slug, $settings, $is_atomic, $element ),
		);
	}

	/**
	 * Extracts the content values from a node's settings, keyed by role.
	 *
	 * @param string               $slug      Widget or element slug.
	 * @param array<string, mixed> $settings  Node settings.
	 * @param bool                 $is_atomic Whether the node is atomic.
	 * @param object|null          $element   The already-resolved widget/element object
	 *                                        (see {@see Elementor_Schema::element()}), so an
	 *                                        unmapped widget's heuristic lookup isn't repeated.
	 * @return array<string, mixed>
	 */
	private static function content_values( $slug, array $settings, $is_atomic, $element = null ) {
		$out = array();

		foreach ( Elementor_Schema::content_controls( $slug, $element ) as $role => $control ) {
			if ( ! array_key_exists( $control, $settings ) ) {
				continue;
			}

			$out[ $role ] = array(
				'control' => (string) $control,
				'value'   => self::render_value( $settings[ $control ], $is_atomic ),
			);
		}

		return $out;
	}

	/**
	 * Renders a setting value as a short display string.
	 *
	 * Atomic values arrive wrapped as {"$$type": ..., "value": ...}; classic media
	 * and url controls arrive as arrays. Both are reduced to something readable.
	 *
	 * @param mixed $value     Raw setting value.
	 * @param bool  $is_atomic Whether the node is atomic.
	 * @return string
	 */
	private static function render_value( $value, $is_atomic ) {
		if ( $is_atomic && is_array( $value ) && array_key_exists( 'value', $value ) ) {
			$value = $value['value'];
		}

		if ( is_array( $value ) ) {
			// Classic media controls carry url/id; url controls carry url.
			foreach ( array( 'url', 'id' ) as $key ) {
				if ( isset( $value[ $key ] ) && is_scalar( $value[ $key ] ) ) {
					return (string) $value[ $key ];
				}
			}
			// Atomic image props nest src.id / src.url.
			if ( isset( $value['src'] ) && is_array( $value['src'] ) ) {
				return self::render_value( $value['src'], false );
			}
			return (string) wp_json_encode( $value );
		}

		if ( is_bool( $value ) ) {
			return $value ? 'true' : 'false';
		}

		$text = (string) $value;

		if ( strlen( $text ) > 500 ) {
			return substr( $text, 0, 497 ) . '...';
		}

		return $text;
	}

	/**
	 * Reads the Elementor-related meta that decides whether a layout renders.
	 *
	 * @param int $post_id Post ID.
	 * @return array<string, mixed>
	 */
	public static function state( $post_id ) {
		$post_id = (int) $post_id;
		$raw     = self::raw( $post_id );

		return array(
			'plugin_active' => Elementor_Schema::available(),
			'pro_active'    => Elementor_Schema::pro_available(),
			'version'       => Elementor_Schema::version(),
			'has_data'      => '' !== $raw,
			'data_bytes'    => strlen( $raw ),
			'edit_mode'     => (string) get_post_meta( $post_id, self::EDIT_MODE_KEY, true ),
			'template_type' => (string) get_post_meta( $post_id, self::TEMPLATE_TYPE_KEY, true ),
			'saved_version' => (string) get_post_meta( $post_id, '_elementor_version', true ),
			'page_template' => (string) get_post_meta( $post_id, '_wp_page_template', true ),
			'edit_url'      => admin_url( 'post.php?post=' . $post_id . '&action=elementor' ),
		);
	}
}
